stages:
  - build-composer
  - build-js
  - deploy

default:
  image: "kellerkinder/pipeline-image:PHP_8.2-NODE_18"

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
  SSH_PRIVATE_KEY: "Private key for ssh connection to deploy server. Add this as a GitLab CI Secret and delete this line"
  SSH_HOST_KEY: "Host key for ssh connection to deploy server. Get this with `ssh-keyscan -H $DEPLOYMENT_IP`. Add this as a GitLab CI Secret and delete this line"
  SHOPWARE_COMPOSER_TOKEN: "You may want to add this as a pipeline secret"
  DEPLOYMENT_DIR: "./.deployment"
  CI: "1" # use `bin/ci` instead of `bin/console`
  DEPLOYMENT_IP: "127.0.0.1" # adjust with your deploy server IP
  NPM_CONFIG_ENGINE_STRICT: "false"
  SHOPWARE_SKIP_THEME_COMPILE: "true" # needed to build the js files inside the ci
  SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS: "1"
  DISABLE_ADMIN_COMPILATION_TYPECHECK: "1"
  DATABASE_URL: ''

composer:
  stage: build-composer
  only:
    refs:
      - main
  before_script:
    - if [[ "$SHOPWARE_COMPOSER_TOKEN" != "" ]]; then composer config bearer.packages.shopware.com "$SHOPWARE_COMPOSER_TOKEN"; fi
  artifacts:
    expire_in: '600'
    paths:
      - auth.json
      - composer.json
      - composer.lock
      - vendor
  script:
    - cd ${CI_PROJECT_DIR} && composer install --no-interaction --optimize-autoloader --no-scripts --ignore-platform-reqs

build-js:
  stage: build-js
  needs: [ composer ]
  only:
    refs:
      - main
  script:
    - ./bin/build-js.sh
  artifacts:
    expire_in: '600'
    untracked: true
    paths:
      - auth.json
      - composer.json
      - composer.lock
      - public
      - vendor

deployment:
  stage: deploy
  needs: [ build-js ]
  only:
    refs:
      - main
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
    - cd ${CI_PROJECT_DIR}/${DEPLOYMENT_DIR} && composer install -no
  script:
    - php vendor/bin/dep deploy stage=production -vvv
